created functions sample
dotnet/aspire-samples pull request #523
Opened 2024-10-28 15:45 UTC by bradygaster

This includes all of the files required for the Functions + Aspire sample to work. Open to feedback!

2024-10-28 21:27 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/global.json
> +{
Should be able to remove this now if you sync with `main`

2024-10-28 21:36 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +	</ItemGroup>
nit: formatting is odd (tabs instead of spaces?)

2024-10-28 21:37 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
This library has licensing constraints that might make it unsuitable for a sample. Pinging @richlander for his input.

2024-10-28 21:40 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +		</None>
```suggestion
		<None Update="host.json" CopyToOutputDirectory="PreserveNewest" />
		<None Update="local.settings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
```

2024-10-28 21:42 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/SecondFunctionApp/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
Why is a specific .gitignore needed for this project?

2024-10-28 21:43 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/SecondFunctionApp/Function1.cs
> +namespace SecondFunctionApp
nit: formatting, use a file-scoped namespace here.

2024-10-28 21:44 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/AppHostTests.cs
> +            new TestEndpoints("ImageGallery.AppHost", new() {
Is this error message in the logs expected? Does it get emitted when running the functions sample outside of tests?
`An error occurred trying to start process 'func' with working directory 'bin/Debug/net9.0/'. No such file or directory`

2024-10-28 21:45 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/SamplesIntegrationTests.csproj
> +    <TargetFramework>net9.0</TargetFramework>
Update the package reference for `Microsoft.Extensions.Diagnostics.Testing` to latest preview version on nuget.org if we're retargeting tests to `net9.0`.

2024-10-28 21:47 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ThumbnailGenerator.cs
> +        string name)
no idea, can fix

2024-10-28 21:47 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/SamplesIntegrationTests.csproj
> +    <TargetFramework>net9.0</TargetFramework>
Hmm we might have to think a bit more about this. Changing this to target `net9.0` means *all* the app host projects being tested will now be running on `net9.0` instead of the version they actually target. Means the tests aren't running against the version used when those samples app hosts' are run normally. We might have to change this to multi-target and update the test data logic to only include app host projects that match the current TFM.

2024-10-28 21:48 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
Would welcome a native way of doing a thumbnail that doesn't not depend on `System.Drawing` or `System.Drawing.Common`

2024-10-28 21:49 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ThumbnailGenerator.cs
> +        string name)
fixed

2024-10-28 21:49 UTC, bradygaster commented on samples/AspireWithAzureFunctions/SecondFunctionApp/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
accidental, can remove.

2024-10-28 21:52 UTC, bradygaster commented on tests/SamplesIntegrationTests/SamplesIntegrationTests.csproj
> +    <TargetFramework>net9.0</TargetFramework>
open to that!

2024-10-28 21:53 UTC, bradygaster commented on tests/SamplesIntegrationTests/AppHostTests.cs
> +            new TestEndpoints("ImageGallery.AppHost", new() {
not sure why that would be happening - pinging @fabiocav for input on this

2024-10-28 21:56 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
[Magick.NET](https://github.com/dlemstra/Magick.NET/) uses Apache 2.0 however the underlying [ImageMagick](https://imagemagick.org/) library it depends on uses a [custom license](https://imagemagick.org/script/license.php) that is seemingly permissive but we'd likely need approval to reference it.

[SkiaSharp] is a .NET wrapper for [Skia](https://skia.org) that's [MIT licensed (and owned by Microsoft 😃)](https://github.com/mono/SkiaSharp/blob/main/LICENSE.txt). The underlying library is [licensed under BSD-3-Clause](https://github.com/google/skia?tab=BSD-3-Clause-1-ov-file#readme). This is likely a good candidate assuming it meets the needs of the sample.

2024-10-28 21:57 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +	</ItemGroup>
used vs code formatter and re-committed/pushed

2024-10-28 21:59 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
Also TBC using `SixLabors.ImageSharp` might be fine given this repo itself is licensed under an OSS license. The [Six Labors Split License](https://github.com/SixLabors/ImageSharp?tab=License-1-ov-file#readme) allows one to use ImageSharp under Apache 2.0 if the referencing work (this sample) is itself licensed under an Open Source or Source Available License.

2024-10-28 22:03 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
How about SkiaSharp?

2024-10-28 22:04 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGalleryFunctions/ImageGalleryFunctions.csproj
> +		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
Oh wait you answered that. :)

2024-10-28 22:05 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/AppHostTests.cs
> +            new TestEndpoints("ImageGallery.AppHost", new() {
Does the functions project work on Ubuntu from the CLI? Are any dependencies required?

Related, if I just clone this project and try to run it I get an error in VS on Windows: `There is no Functions runtime available that matches the version specified in the project`.

![image](https://github.com/user-attachments/assets/37352b5f-912f-4728-bf11-525031a4ba55)

How can we improve that experience? There's no indication in VS that anything is missing:

![image](https://github.com/user-attachments/assets/f579809b-bf3a-498e-afc5-b33e8fed5f32)

2024-10-28 22:29 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/AppHostTests.cs
> +            new TestEndpoints("ImageGallery.AppHost", new() {
Spoke to @bradygaster offline about this. I had to go into **Tools -> Options -> Projects and Solutions -> Azure Functions** in VS and click the **Check for updates** button to get this to work. I already had the Azure workload installed but had to find and click this button once it seems to get **any** version of the functions runtime installed locally. This isn't a great experience for first-time consumers.

![image](https://github.com/user-attachments/assets/e099379f-b31a-4906-abfd-aa25b3272b38)

How does this work on non-Windows or outside of VS?

2024-10-28 23:07 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.Web/Components/Layout/NavMenu.razor
> +    <nav class="flex-column">
I think you're missing some markup changes from the latest updates to the templates here. This is what I see when running this locally, you can see the padding of the menu item looks off:

![image](https://github.com/user-attachments/assets/83a4f844-5485-4c5b-a0fa-d9196878a1b6)

2024-10-28 23:08 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.Web/Components/Layout/NavMenu.razor
> +    <nav class="flex-column">
i can resolve that! thanks for reviewing. i'll update the UX layer tonight

2024-10-28 23:36 UTC, DamianEdwards commented
@bradygaster this sample will need a README.md too

2024-10-29 00:29 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/SamplesIntegrationTests.csproj
> +    <TargetFramework>net9.0</TargetFramework>
OK I have this change locally. Will push and see how it fares on CI:

![image](https://github.com/user-attachments/assets/e1b033a0-4731-4ed9-b0a6-66c22ef6c834)

2024-10-29 00:30 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/SamplesIntegrationTests.csproj
> +    <TargetFramework>net9.0</TargetFramework>
I did this.

2024-10-29 00:30 UTC, DamianEdwards commented on tests/SamplesIntegrationTests/AppHostTests.cs
> +            new TestEndpoints("ImageGallery.AppHost", new() {
And the answer: https://learn.microsoft.com/en-us/azure/azure-functions/functions-develop-local#local-development-environments

I updated the `ci.yml` to install the command-line functions runtime.

2024-10-29 00:47 UTC, DamianEdwards requested changes
Tests are passing now, for both `net8.0` and `net9.0`.

Just need the nav menu issue fixed and a README.md created.

2024-10-29 22:11 UTC, bradygaster commented
@DamianEdwards - tweaked the UX and added a readme, along with a few renames to be consistent. lmk if anything else is requisite, thanks for the review.

2024-10-29 22:31 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/README.md
> +urlFragment: "aspire-functions"
Probably good to be a bit more specific, e.g. `aspire-azure-functions`

2024-10-29 22:32 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/README.md
> +- [.NET 9 SDK](https://dotnet.microsoft.com/download/dotnet/8.0)
```suggestion
- [.NET 9 SDK](https://dotnet.microsoft.com/download/dotnet/9.0)
```

2024-10-29 22:33 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/README.md
> +- **Optional** [Visual Studio 2022 17.12](https://visualstudio.microsoft.com/vs/preview/)
Is the plan to not merge this PR until we GA 9.0? I'm not sure how I feel about having a sample that requires custom NuGet feeds in `main` so I think we should hold this until GA if it can't be made to work with bits from nuget.org ATM.

2024-10-29 22:40 UTC, DamianEdwards commented
@bradygaster just checking, your intent was to remove the side navbar completely? This is what I see now:
![image](https://github.com/user-attachments/assets/bedbccf7-c9e9-48da-a6a9-23ddceac7235)

2024-10-29 22:50 UTC, bradygaster commented on samples/AspireWithAzureFunctions/README.md
> +- **Optional** [Visual Studio 2022 17.12](https://visualstudio.microsoft.com/vs/preview/)
we can remove the custom nuget feed, i think. will try

2024-10-29 22:57 UTC, captainsafia commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/Properties/serviceDependencies.json
We should commit this file into the sample. It looks like a Connected Service-ism that we'll eventually want Visual Studio not to generate for Aspire-enabled projects.

2024-10-29 22:57 UTC, captainsafia commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/Properties/serviceDependencies.local.json
Ditto here -- this shouldn't be needed.

2024-10-30 05:13 UTC, bradygaster commented
@DamianEdwards and @captainsafia - anything else?

2024-10-30 14:41 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/Properties/serviceDependencies.local.json
I see these are deleted now, but do we need to update `.gitignore` so they don't come back if VS adds them back again?

2024-10-30 15:39 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/Properties/serviceDependencies.local.json
they only get dropped on file -> new afaik. i think we're okay.

2024-10-30 18:06 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/ImageGallery.Functions.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
The whitespace formatting of this file went back to TABS. We use SPACES here bro 😉

2024-10-30 18:08 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/README.md
> +- [.NET 9 SDK](https://dotnet.microsoft.com/download/dotnet/8.0)
This is still linking to the 9.0 page?

2024-10-30 18:55 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/ImageGallery.Functions.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
@DamianEdwards fixed, hopefully, or we need to yell at whoever owns the spaces not tabs checkbox. :)

2024-10-30 18:57 UTC, bradygaster commented on samples/AspireWithAzureFunctions/README.md
> +- [.NET 9 SDK](https://dotnet.microsoft.com/download/dotnet/8.0)
derp

2024-10-30 20:03 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.Web/Components/Layout/NavMenu.razor
> +    <nav class="flex-column">
Attention @DamianEdwards - The ASP.NET Core 9.0 Blazor template seems to have updated their bootstrap versions, but not the HTML to use the correct classes. As a result, when you do file new Blazor app with 9.0 it's broken:

![image](https://github.com/user-attachments/assets/1df40f67-14be-45d3-8246-25f7ffec5fd9)

2024-10-30 22:18 UTC, danroth27 commented on samples/AspireWithAzureFunctions/ImageGallery.Web/Components/Layout/NavMenu.razor
> +    <nav class="flex-column">
@IEvangelist Should be fixed in .NET 9 GA: https://github.com/dotnet/aspnetcore/issues/58214

2024-10-30 23:06 UTC, DamianEdwards approved these changes
Good from my POV now. Couple of comments from @captainsafia.

2024-10-31 08:44 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/ThumbnailGenerator.cs
> +            int targetHeight = 128;
done in updated function code

2024-10-31 08:44 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/ThumbnailGenerator.cs
> +            var containerClient = blobServiceClient.GetBlobContainerClient("thumbnails");
done!

2024-10-31 08:45 UTC, bradygaster commented
@DamianEdwards and @captainsafia - i got some great updates from @IEvangelist to clean up the UX. added those and took Safia's feedback into consideration and got them both in this push.

2024-10-31 18:52 UTC, captainsafia commented
> @DamianEdwards and @captainsafia - i got some great updates from @IEvangelist to clean up the UX. added those and took Safia's feedback into consideration and got them both in this push.

Noted. @IEvangelist mentioned running into some test issues with these changes. Did https://github.com/dotnet/aspire-samples/pull/523/commits/f92eeacf53c6b425e0359042e0a65ffad5d8ee4c resolve this? I don't think it's necessary for us to use `WithHostStorage` in the sample code so if that works around the race condition then that is fine by me.

2024-10-31 19:37 UTC, IEvangelist commented
> > @DamianEdwards and @captainsafia - i got some great updates from @IEvangelist to clean up the UX. added those and took Safia's feedback into consideration and got them both in this push.
> 
> Noted. @IEvangelist mentioned running into some test issues with these changes. Did [f92eeac](https://github.com/dotnet/aspire-samples/commit/f92eeacf53c6b425e0359042e0a65ffad5d8ee4c) resolve this? I don't think it's necessary for us to use `WithHostStorage` in the sample code so if that works around the race condition then that is fine by me.

Yes, I removed that from the sample, and everything is again green!

2024-10-31 20:17 UTC, captainsafia approved these changes
LGTM! Minor comment on indentation inline.

I ran into some weird quirks with the UI (no progress indicator and image population doesn't seem to work in Safari) but I don't think these should be blocking.

2024-10-31 20:17 UTC, captainsafia commented on samples/AspireWithAzureFunctions/ImageGallery.AppHost/Program.cs
> +           .WithReference(queues)
Nit: I think we can decrease the indentation here.

2024-10-31 23:11 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.AppHost/Program.cs
> +           .WithReference(queues)
Yeah this doesn't match the alignment/formatting we use elsewhere.

2024-10-31 23:14 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/Program.cs
> +
nit: multiple blank lines

2024-10-31 23:15 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +        await base.StartAsync(cancellationToken);
I don't think this is required.

2024-10-31 23:18 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +                        "Message received but was either null or without value.");
This seems overly wrapped to new line. What column width are you assuming? We usually work to a max width of ~140 cols I think.

2024-10-31 23:27 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/ImageGallery.Functions.csproj
> +    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
?

2024-10-31 23:28 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.Shared/ImageGallery.Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
What is this project for? Why do we need a "shared" project that's separate from the service defaults project?

2024-10-31 23:32 UTC, DamianEdwards requested changes
Some new comments

2024-11-01 16:18 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.Shared/ImageGallery.Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
I thought we weren't supposed to put any shared code into the service defaults project. @IEvangelist and i have both been publicly shamed for this on separate occasions. :)

2024-11-01 18:42 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.Shared/ImageGallery.Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Yeah, I agree with @bradygaster here. You specifically told us that the service defaults project was intended for something other than shared models. 🙄 That eShop sample is demonstrating all similar additions to what the template includes, that is, extension methods. Shared models is not something I'd expect to have in a project named _*.ServiceDefaults_.

2024-11-01 18:44 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +        await base.StartAsync(cancellationToken);
This was likely my doing. In docs, we strive for a column width of 80 (I know, narrow), but the reasoning is to try to avoid horizontal scrolling, and we were planning on pulling this sample into docs for part of a tutorial.

2024-11-01 18:44 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.AppHost/Program.cs
> +           .WithReference(queues)
Same reasoning listed here: https://github.com/dotnet/aspire-samples/pull/523#discussion_r1826177347

2024-11-01 18:45 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/Program.cs
> +
```suggestion
```

2024-11-01 18:47 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +                        "Message received but was either null or without value.");
This was likely my doing. In docs, we strive for a column width of 80 (I know, narrow), but the reasoning is to try to avoid horizontal scrolling, and we were planning on pulling this sample into docs for part of a tutorial.

2024-11-01 18:47 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/Program.cs
> +
I think this is part of the template too, but agree - I removed it.

2024-11-01 19:18 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/Program.cs
> +
We typically leave a blank line at the end of files

2024-11-01 20:16 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.Shared/ImageGallery.Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
OK fair enough. Might I suggest a name like a little more specific than "Shared" though, to make it clearer, e.g. "ImageGallery.DTOs" or "ImageGallery.Model", etc.

2024-11-01 20:18 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +                        "Message received but was either null or without value.");
This makes it hard to enforce standards consistently. I think 80 is too restrictive as a general standard. I think I'd prefer to keep this repo for standalone samples that show up in the sample gallery and not have to be concerned with extra constraints that come from the code being embedded in docs too.

2024-11-01 20:23 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +        await base.StartAsync(cancellationToken);
it is required in this sample. i'm not sure if it's a known bug or not, but, **at least in this example**, `ExecuteAsync` never fires unless it calls `base.StartAsync`. Not sure if it's a bug in the product (feels like it isn't by design, like `ExecuteAsync` should just start without the need for `base.StartAsync` to be called, but, seems like the case. 

I can file an issue if folks agree the product should "just work," but i think acceptance of this PR with this in is fine.

2024-11-01 20:26 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +                        "Message received but was either null or without value.");
I'm going to leave this as @IEvangelist has it since it'll be used in content.

2024-11-01 20:28 UTC, bradygaster commented on samples/AspireWithAzureFunctions/ImageGallery.Shared/ImageGallery.Shared.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
I think the Shared project is fine being left in. Resolving as-is. I've been towing the line on service defaults projects being not the place for shared code specific to the app's domain based on feedback we both received from you on this early on. This precedent has been set, let's leave it alone.

2024-11-01 20:39 UTC, DamianEdwards commented on samples/AspireWithAzureFunctions/ImageGallery.FrontEnd/StorageWorker.cs
> +        await base.StartAsync(cancellationToken);
Ah ok. I admit I don't usually use StartAsync at all in my background services so this must mean that base.StartAsync calls ExecuteAsync, which I still find not aligned with much of the rest of virtual members in types in Core but oh well.

2024-11-04 14:04 UTC, IEvangelist commented on samples/AspireWithAzureFunctions/ImageGallery.Functions/ImageGallery.Functions.csproj
> +    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
See here: https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj#L40-L44

2024-11-04 17:12 UTC, DamianEdwards approved these changes
Thanks for all the work on this one!

2024-11-04 17:12 UTC, merged